### PR TITLE
refactor: factorize DB methods, use DB pool and connection from context

### PR DESCRIPTION
**Pull request by bolinocroustibat**
Related to [issue #1395](https://github.com/datagouv/data.gouv.fr/issues/1395), but not fully closing the issue yet.
Also closes https://github.com/datagouv/hydra/pull/55.

This PR has been split into 3 parts for easier reviewing.
1) **This PR**:  refactoring in order to prepare for new routes (_Note: It had already partly reviewed in previous state of [PR #104](https://github.com/datagouv/hydra/pull/104)_)
2) Adding new route to force a crawl: [PR #104](https://github.com/datagouv/hydra/pull/104)
3) Adding resource statuses and a resource status route: [PR #113](https://github.com/datagouv/hydra/pull/113)

**Details of this PR:**
- Refactor project structure to use DB classes for each DB table, with their factorized DB methods. This was necessary to improve readability and maintainability since routes and cli use common DB queries. This is extremely similar to what has been started in this PR that has been opened for a long time: https://github.com/datagouv/hydra/pull/55. This will also strongly helps to refactor with an ORM later (shttps://github.com/https://github.com/datagouv/hydra/issues/29) and make the whole project more REST/CRUD/MVC standardized.
- Always use DB pool from app context instead of passing it to DB functions through the requests
- Put schemas in dedicated `schemas/` directory
- Add docstrings to some functions to improve documentation

### CODE REVIEW

**Review by magopian — COMMENTED** [review]
Thanks for splitting the PR, it's indeeded more focused, and thus easier to review 🙏 
This looks good to me, bearing in mind that I'm not knowledgeable about the codebase, and haven't tried running the code myself.

**Comment by bolinocroustibat** [comment]
> Thanks for splitting the PR, it's indeeded more focused, and thus easier to review 🙏 This looks good to me, bearing in mind that I'm not knowledgeable about the codebase, and haven't tried running the code myself.

Yes that's not an easy PR to review, that's no problem. Can you re-approve? Seems I cannot merge since I appended a marge commit since your last approbation.

**Review by magopian — APPROVED** [review]
Yep, sure ;)

**Review by maudetes — APPROVED** [review]
I haven't read all in detail, but seems fair! Thank you for this refacto

**Pull request merged**
